-- MySQL Script generated by MySQL Workbench
-- Wed Aug 10 09:06:30 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Carlos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Carlos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Carlos` DEFAULT CHARACTER SET utf8 ;
USE `Carlos` ;

-- -----------------------------------------------------
-- Table `Carlos`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carlos`.`Endereco` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Carlos`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carlos`.`Cliente` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `fkEndereco` INT NOT NULL,
  `numeroCasa` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`idCliente`),
  INDEX `fkEndereco_idx` (`fkEndereco` ASC) VISIBLE,
  CONSTRAINT `fkEndereco`
    FOREIGN KEY (`fkEndereco`)
    REFERENCES `Carlos`.`Endereco` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Carlos`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carlos`.`Telefone` (
  `idTelefone` INT NOT NULL AUTO_INCREMENT,
  `ddd` DECIMAL(2) NOT NULL,
  `numeroTelefone` DECIMAL(9) NOT NULL,
  `fkCliente` INT NOT NULL,
  PRIMARY KEY (`idTelefone`),
  INDEX `fkCliente_idx` (`fkCliente` ASC) VISIBLE,
  CONSTRAINT `fkCliente`
    FOREIGN KEY (`fkCliente`)
    REFERENCES `Carlos`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Carlos`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carlos`.`Venda` (
  `idVenda` INT NOT NULL,
  `valorTotal` FLOAT NOT NULL,
  `fkCliente` INT NOT NULL,
  `diaVenda` DATETIME NOT NULL,
  PRIMARY KEY (`idVenda`),
  INDEX `fkCliente_idx` (`fkCliente` ASC) VISIBLE,
  CONSTRAINT `fkCliente`
    FOREIGN KEY (`fkCliente`)
    REFERENCES `Carlos`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Carlos`.`ProdutosProntos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carlos`.`ProdutosProntos` (
  `idProdutosProntos` INT NOT NULL AUTO_INCREMENT,
  `quantidade` DECIMAL(4) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `qtdMinima` DECIMAL(4) NOT NULL,
  `valorVenda` FLOAT NOT NULL,
  PRIMARY KEY (`idProdutosProntos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Carlos`.`ItensVendidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carlos`.`ItensVendidos` (
  `idItensVendidos` INT NOT NULL AUTO_INCREMENT,
  `quantidade` DECIMAL(4) NOT NULL,
  `fkVenda` INT NOT NULL,
  `fkProdutosProntos` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `valorVenda` FLOAT NOT NULL,
  PRIMARY KEY (`idItensVendidos`),
  INDEX `fkVenda_idx` (`fkVenda` ASC) VISIBLE,
  INDEX `fkProdutosProntos_idx` (`fkProdutosProntos` ASC) VISIBLE,
  CONSTRAINT `fkVenda`
    FOREIGN KEY (`fkVenda`)
    REFERENCES `Carlos`.`Venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkProdutosProntos`
    FOREIGN KEY (`fkProdutosProntos`)
    REFERENCES `Carlos`.`ProdutosProntos` (`idProdutosProntos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Carlos`.`Ingredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carlos`.`Ingredientes` (
  `idIngredientes` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `quantidade` DECIMAL(4) NOT NULL,
  `valorMercado` FLOAT NOT NULL,
  `qtdMinima` DECIMAL(4) NOT NULL,
  `dataCompra` DATETIME NOT NULL,
  PRIMARY KEY (`idIngredientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Carlos`.`Agenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carlos`.`Agenda` (
  `idAgenda` INT NOT NULL AUTO_INCREMENT,
  `diaEntrega` DATETIME NOT NULL,
  `fkVenda` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  `pago` TINYINT NOT NULL,
  PRIMARY KEY (`idAgenda`),
  INDEX `fkVenda_idx` (`fkVenda` ASC) VISIBLE,
  CONSTRAINT `fkVenda`
    FOREIGN KEY (`fkVenda`)
    REFERENCES `Carlos`.`Venda` (`idVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Carlos`.`itensIngredientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Carlos`.`itensIngredientes` (
  `iditensIngredientes` INT NOT NULL AUTO_INCREMENT,
  `fkIngredientes` INT NOT NULL,
  `fkprodutosProntos` INT NOT NULL,
  `qtdUsada` DECIMAL(4) NOT NULL,
  PRIMARY KEY (`iditensIngredientes`),
  INDEX `fkIngredientes_idx` (`fkIngredientes` ASC) VISIBLE,
  INDEX `fkProdutosProntos_idx` (`fkprodutosProntos` ASC) VISIBLE,
  CONSTRAINT `fkIngredientes`
    FOREIGN KEY (`fkIngredientes`)
    REFERENCES `Carlos`.`Ingredientes` (`idIngredientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fkProdutosProntos`
    FOREIGN KEY (`fkprodutosProntos`)
    REFERENCES `Carlos`.`ProdutosProntos` (`idProdutosProntos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
